### ISSUE TITLE
link for repo to 2019 Nature paper "Mapping disparities in education across low- and middle-income countries"

### ISSUE THREAD

**Issue by timriffe** [ihmeuw/lbd#1]
Hi!

This paper cites your repository as containing supplementary code for the paper [Mapping disparities in education across low- and middle-income countries](https://www.nature.com/articles/s41586-019-1872-1), specifically `http://github.com/ihmeuw/lbd/tree/edu-lmic-2019`, but this link is dead. Following up the tree, I see other papers get links to bespoke repositories in this repository's `README`. Presumably the provided link wasn't final, and the repository has since been migrated. In this case, could you please add a link in the readme along with the others?

Thanks!

Tim

**Comment by zimaaron** [comment]
Hi Tim -

Sorry for the dead link and any confusion. The code usually goes live on
publication date and due to the holidays this was missed. The code is now
up and the link should work.

All the best,
Aaron

**Comment by timriffe** [comment]
Thanks that was fast!
